version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  movie-api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./movieApi.dockerfile  # Adjust this line if necessary
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      GREENLIGHT_DB_DSN: "postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}?sslmode=disable"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  postgres-db:
